service: todo

frameworkVersion: '3'

custom:
  TableName: todoTable

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:        
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ TodoTable, Arn]
        

functions:
  getAllTasks:
    handler: src/functions.getAllTasks
    events:
      - httpApi:
          method: GET
          path: /
  taskById:
    handler: src/functions.taskById
    events:
      - httpApi:
          method: GET
          path: /{id}
  deleteTask:
    handler: src/functions.deleteTask
    events:
      - httpApi:
          method: DELETE
          path: /{id}
  createTask:
    handler: src/functions.createTask
    events:
      - httpApi:
          method: POST
          path: /
  updateTask:
    handler: src/functions.updateTask
    events:
      - httpApi:
          method: PUT
          path: /


resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.TableName}
  
